Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentsDB.Data;
using StudentsDB.Models;

namespace StudentsDB.Controllers
{
    public class AddressesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AddressesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Address.ToListAsync());
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
          
            var address = await _context.Address
                .FirstOrDefaultAsync(m => m.AddrId == id);
         
            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Addresses/Create

        [HttpPost]

        public async Task<IActionResult> Create([Bind("AddrId,Name,Addr")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }
        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.AddrId == id);
        }
        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
           

            var address = await _context.Address.FindAsync(id);
          
            return View(address);
        }

        // POST: Addresses/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddrId,Name,Addr")] Address address)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
              
                }
                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
           
            var address = await _context.Address
                .FirstOrDefaultAsync(m => m.AddrId == id);
         

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Address.FindAsync(id);
            _context.Address.Remove(address);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

      
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentsDB.Data;
using StudentsDB.Models;

namespace StudentsDB.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
        

            var courses = await _context.Courses
                .FirstOrDefaultAsync(m => m.CID == id);
            
            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }
        private bool CoursesExists(int id)
        {
            return _context.Courses.Any(e => e.CID == id);
        }
        // POST: Courses/Create

        [HttpPost]

        public async Task<IActionResult> Create([Bind("CID,CourseName,Description")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                _context.Add(courses);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var courses = await _context.Courses.FindAsync(id);
         
            return View(courses);
        }

        // POST: Courses/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CID,CourseName,Description")] Courses courses)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                  
                }
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            

            var courses = await _context.Courses
                .FirstOrDefaultAsync(m => m.CID == id);
          
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var courses = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(courses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

     
    }
}

Controllers/StudentInfosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentsDB.Data;
using StudentsDB.Models;

namespace StudentsDB.Controllers
{
    public class StudentInfosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentInfosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: StudentInfos
        public async Task<IActionResult> Index()
        {
            return View(await _context.StudentInfos.ToListAsync());
        }

        // GET: StudentInfos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
           
            var studentInfos = await _context.StudentInfos
                .FirstOrDefaultAsync(m => m.StdId == id);
          
            return View(studentInfos);
        }

        // GET: StudentInfos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentInfos/Create

        [HttpPost]

        public async Task<IActionResult> Create([Bind("StdId,FirstName,LastName,Gender,MyProperty")] StudentInfos studentInfos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentInfos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(studentInfos);
        }

        // GET: StudentInfos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            var studentInfos = await _context.StudentInfos.FindAsync(id);
         
            return View(studentInfos);
        }

        // POST: StudentInfos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StdId,FirstName,LastName,Gender,MyProperty")] StudentInfos studentInfos)
        {
          
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentInfos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                }
                return RedirectToAction(nameof(Index));
            }
            return View(studentInfos);
        }

        // GET: StudentInfos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
         

            var studentInfos = await _context.StudentInfos
                .FirstOrDefaultAsync(m => m.StdId == id);
           

            return View(studentInfos);
        }

        // POST: StudentInfos/Delete/5
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var studentInfos = await _context.StudentInfos.FindAsync(id);
            _context.StudentInfos.Remove(studentInfos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentInfosExists(int id)
        {
            return _context.StudentInfos.Any(e => e.StdId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Students System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Students </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="StudentInfos" asp-action="Index">Student Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Addresses" asp-action="Index">Address</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StudentsDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>